### PR TITLE
changes and improvements in form

### PR DESCRIPTION
**Pull request by ameg47**
-Moved error elements to the correct position
-Fixed errors with email and username validations
-Added live validation for password (still not convinced tho, let me know what u think once u tried it)
-Added text next to "contraseña" specifying amount of characters needed
-Switched select input for datalist in category as suggested by Matias  (not sure about this either, the style cannot be modified since it depends on the browser)

### CODE REVIEW

**Comment by ameg47** [comment]
image

**Comment by ameg47** [comment]
switched back to select cause datalist sucks with react

**Review by maujpok — APPROVED** [review]

**Review by Noheliajoeliana — APPROVED** [review]
Super agus, pilas que te está generando conflictos, parecen fáciles de resolver así que arreglalos antes de mergear.

**Comment by ameg47** [comment]
si era pq antonio mergeo antes

**Pull request merged**
